export const LOGINACTION = 'LOGINACTION'

export const SETPROFILEACTION = 'SETPROFILEACTION'

export const SETEDITACTION = 'SETEDITACTION'

export const UPDATEUSERINFO = 'UPDATEUSERINFO'

export const LOGOUT = 'LOGOUT'

// 更新频道数据
export const UPDATECHANNELS = 'UPDATECHANNELS'

export const SETRESTCHANNELS = 'SETRESTCHANNELS'
export const UPDATEACTIVECHANNELKEY = 'UPDATEACTIVECHANNELKEY'
export const DELCHANNEL = 'DELCHANNEL'

export const ADDCHANNEL = 'ADDCHANNEL'

export const UPDATEARTICLE = 'UPDATEARTICLE'
